### PR TITLE
Do not load duplicate model entries in GUI

### PR DESCRIPTION
**Pull request by signedav**
IMHO this is a solid solution, but I'm not sure if it could be nicer with something like `if any(model['name'] in s.data(int(Qt.DisplayRole)) for s in self):`...

#151

### CODE REVIEW

**Comment by m-kuhn** [comment]
Yes, looks like a solid solution. Since (at least to me) it's not intuitively readable, a comment on what it does would be good

**Comment by m-kuhn** [comment]
Hmm... I think the `fix #xyz` part was missing in the commit message. Can you close the issue?

**Comment by signedav** [comment]
So it needs to be in the commit message, right? Sorry for that. Wouldn't happen again :slightly_smiling_face:

**Comment by m-kuhn** [comment]
Maybe it also works if it's in the description, but it needs to have `fix` or another [supported keyword](https://help.github.com/articles/closing-issues-using-keywords/) on the same line

**Comment by signedav** [comment]
I added the keyword with edit, later on. So probably it does not work like this. Thanks.

**Pull request merged**
