### PR TITLE
Recursive search modeldir

### PR DESCRIPTION
**Pull request by juusechec**
Recursive search of ilimodels in modeldir

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nice.
Is there ever a situation where we want this to be disabled?
I'm wondering if we can skip the option and always search recursively?

**Comment by juusechec** [comment]
With @gacarrillor we think is possible that the list of models in all sub-directories of a complex repository, collapse unnecessary the cache and the search.

**Comment by m-kuhn** [comment]
Do you need to disable recursivity on your current repository?

For context: it works reliably with all swiss models (from dozens of different domains and government levels, which are aggregated from many cascading repositories).

**Comment by juusechec** [comment]
Done the suggested change.

**Comment by m-kuhn** [comment]
Thanks :tada:

**Pull request merged**
