### PR TITLE
Fix domains for layers with multiple geometries

### LINKED ISSUE #116: Relations for tables with several geometry fields
Relations are not being propagated to layers with multiple geometry attributes when loaded to QGIS.

For instance, the `KbS_LV95_V1_3` model from INTERLIS repositories has the `Belasteter_Standort` class with point and polygon geometries. QGIS loads the PostgreSQL table `belasteter standort` as 2 layers (one per geometry type) called equally but only the one with the point geometry gets the relations.

@m-kuhn, I think this a QGIS issue.

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #116

### CODE REVIEW

**Comment by m-kuhn** [comment]
@gacarrillor what do you think about this PR, does this look good to you and fix the problems?

**Comment by gacarrillor** [comment]
It looks goot to me, this is very close to what is expected! However, some relations are still missing in our Point table, as you can see comparing both forms:

Polygon table:
terreno_poligono

Point table:
terreno_punto

**Comment by gacarrillor** [comment]
@m-kuhn Just tested the merged code... What I said in my latest comment is still happening.

**Comment by m-kuhn** [comment]
Yes, I am fully aware, but thought that this fix alone is worth merging as well. I'll look into the other one soon.

**Pull request merged**
