### PR TITLE
Flexible completion dropdown on model lineedit

### PR DESCRIPTION
**Pull request by signedav**
Means it shows the filtered list if you change the original text.
If you click inside a lineedit with content it does not show the list until you change something.
If you click inside an empty lineedit it shows the unfiltered list.
If you delete the text of the lineedit it shows the unfiltered list.

Looks kind of like this:

select_completion

- [x] on Generate
- [x] on import
- [x] on export
- [x] fix ugly GUI
- [x] display only the models from ili-file

It's about #212

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nice
Don't forget the `fixes #212` ;)

**Comment by signedav** [comment]
And this looks like this:

models

What do you think @m-kuhn ?

**Comment by m-kuhn** [comment]
Looking good!

Can the placeholder text be set to the default model name (instead of "Search model in from file") if an ili file is set?

**Comment by signedav** [comment]
It already sets the default model name when file is chosen -> when you then delete the model name and make the line edit empty, the placeholder-text appears.

**Comment by m-kuhn** [comment]
To see the popup, you have to clear the line edit and therefore loose the information what the default model was.

On the other hand with the placeholder text, the information about the default model would always stay available and it's one less click to get to the popup (only select the line edit, no need to delete)

Or am I missing something?

**Comment by m-kuhn** [comment]
I'm not sure from your screencast if the default state is empty or not, I would expect it to be empty.

If it's empty it will either need to call ili2db with --models and the default model OR call ili2db without a --models parameter

**Comment by signedav** [comment]
That's the point. The user does not know if it's empty or not. What does he expect? I would say he expects when the placeholder is "Search for model..." that it's empty and if the placeholder is "Exceptional..." it is the default model called "Exceptional..."

My question is, does / should the generator create the project by the default model if "no model" (empty field) is selected? If yes, then I would make the default value the placeholder. But if the generator creates a project with no model (or empty model / or all the models), then I would take the "Search for model..." for placeholder...

**Comment by signedav** [comment]
Just to know:

selected Model is **_Nutzungsplanung_LV95_V1_1_** (default value):
```
java -jar /home/david/dev/opengisch/projectgenerator/projectgenerator/libili2db/bin/ili2pg-3.11.2/ili2pg.jar --schemaimport --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --strokeArcs --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --importTid --smart1Inheritance --defaultSrsCode 2056 --setupPgExt --dbhost 127.0.0.1 --dbport 5432 --dbusr postgres --dbpwd ****** --dbdatabase import --dbschema test_06 --models Nutzungsplanung_LV95_V1_1 /home/david/doc/clients/SH/Nutzungsplanung_V1_1.ili
```
takes **_Nutzungsplanung_LV95_V1_1_**.

selected Model is **_Nutzungsplanung_LV03_V1_1_**:
```
java -jar /home/david/dev/opengisch/projectgenerator/projectgenerator/libili2db/bin/ili2pg-3.11.2/ili2pg.jar --schemaimport --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --strokeArcs --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --importTid --smart1Inheritance --setupPgExt --dbhost 127.0.0.1 --dbport 5432 --dbusr postgres --dbpwd ****** --dbdatabase import --dbschema test_06 --models Nutzungsplanung_LV03_V1_1 /home/david/doc/clients/SH/Nutzungsplanung_V1_1.ili
```
takes **_Nutzungspalnung_LV03_V1_1_**.

selected Model is empty:
```
java -jar /home/david/dev/opengisch/projectgenerator/projectgenerator/libili2db/bin/ili2pg-3.11.2/ili2pg.jar --schemaimport --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --strokeArcs --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --importTid --smart1Inheritance --defaultSrsCode 2056 --setupPgExt --dbhost 127.0.0.1 --dbport 5432 --dbusr postgres --dbpwd ****** --dbdatabase import --dbschema test_06 /home/david/doc/clients/SH/Nutzungsplanung_V1_1.ili

```
takes no model (in ili2db AFAIK the default model)

**Pull request merged**
