### PR TITLE
Make variables for import and export xtf file settings independent

### PR DESCRIPTION
**Pull request by seralra96**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Hmmm... I would expect that people are mostly exporting from the same database after importing into it, but I'm not sure. Do you have different experiences there?

**Comment by gacarrillor** [comment]
Definitely, we just want to make XTF file setting independent for Import and Export dialogs and don't intent to touch other settings. 

The rationale is that if a user imports an XTF, modifies data in QGIS and wants to export to XTF, the XTF file that appears in the Export dialog is the same she used when importing, which may lead her to made a mistake and overwrite the XTF she imported data from.

**Comment by m-kuhn** [comment]
Is it just the filename?

**Comment by m-kuhn** [comment]
Ah yes, sounds good 👍

**Pull request merged**
